
trigger:
- master

pool:
 name: raos-pool

steps:
- script: cd /home/azureuser/myagent/_work/1/s;mvn package

  displayName: build
- script: scp/home/azureuser/myagent/_work/1/s/webapp/target/webapp.war azureuser@130.107.50.30:/var/lib/tomcat 10/webapp/mytestapp.war
  displayName:  DeployToqa

