
trigger:
- master

pool:
  name: raos-pool

steps:
- script: cd /home/azureuser/myagent/_work/1/s;mvn package
  displayName: build
- script: scp /home/azureuser/myagent/_work/1/s/target/webapp.war azureuser@130.107.50.30:/var/lib/tomcat10/webapps/mytestapp.war
  displayName: 'DeployToqa'


