
trigger:
- master

pool:
  name: raos-pool

steps:
- script: cd /home/azureuser/myagent/_work/1/s;mvn package
  displayName: Build
- script: sudo cp /home/azureuser/myagent/_work/1/s/webapp/target/webapp.war /var/lib/tomcat10/webapps/mytestapp.war

  displayName: DeployToqa

